import { Inter } from 'next/font/google'
import './globals.css'
import AOS from '@/components/AOS/AOS'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tanjil Ahamed Portfolio',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html className='bg-black' lang="en">
      <AOS></AOS>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
